declare type Values<T> = T[keyof T];

declare module "~/styles/variables.module.scss" {
  const classes: {
    fontExtraExtraLarge: string;
    fontExtraLarge: string;
    fontLarge: string;
    fontMedium: string;
    fontSmall: string;
    fontExtraSmall: string;
    fontExtraExtraSmall: string;
    spacingXxsmall: string;
    spacingXsmall: string;
    spacingSmall: string;
    spacingMedium: string;
    spacingLarge: string;
    spacingXlarge: string;
    spacingGuttersmall: string;
    spacingGutter: string;
    spacingHeader: string;
    spacingFooter: string;
    spacingMaxWidth: string;
    spacingHeaderTop: string;
    spacingXxsWidth: string;
    spacingXsWidth: string;
    spacingWidth: string;
    spacingLWidth: string;
    spacingXlWidth: string;
    spacingXxlWidth: string;
    colorWhite: string;
    colorBlack: string;
    colorTransparentBlack: string;
    colorPrimary: string;
    colorPrimaryOpacity: string;
    colorActive: string;
    colorActiveOpacity: string;
    colorGreen: string;
    colorRed: string;
    colorYellow: string;
    colorOrange: string;
    colorPurple: string;
    colorTeal: string;
    colorTextUltraLight: string;
    colorTextLight: string;
    colorTextMedium: string;
    colorTextDark: string;
    colorPrimaryBackground: string;
    colorSecondaryBackground: string;
    colorCard: string;
    colorOrangeLight: string;
    colorRedLight: string;
    colorGreenLight: string;
    colorDivider: string;
    colorBackground: string;
    colorStatusBarColor: string;
    shadow: string;
  };
  export default classes;
}
